# Source: lighthouse/templates/webhooks-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-webhooks
  labels:
    chart: "lighthouse-1.5.16"
    app: lighthouse-webhooks
    git.jenkins-x.io/sha: annotate
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    checksum/config: 7b7bd24a7a7528b9ef9ec465d1a8392ee0b61b99d86b8926429790a0522a7d37
    meta.helm.sh/release-name: 'lighthouse'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-webhooks
  template:
    metadata:
      labels:
        app: lighthouse-webhooks
      annotations:
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
        jenkins-x.io/hash: '86a9f756efc604aa96f7b893c0ab01b4b2009a6194529815738fa046f44117e8'
    spec:
      serviceAccountName: lighthouse-webhooks
      containers:
        - name: lighthouse-webhooks
          image: ghcr.io/jenkins-x/lighthouse-webhooks:1.5.16
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=jx"
          env:
            - name: "GIT_KIND"
              value: "github"
            - name: "LH_CUSTOM_TRIGGER_COMMAND"
              value: "jx"
            - name: "GIT_SERVER"
              value: "https://github.com"
            - name: "GIT_USER"
              value: siddharth271
            - name: "GIT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: lighthouse-oauth-token
                  key: oauth
            - name: "HMAC_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: "lighthouse-hmac-token"
                  key: hmac
                  optional: false
            - name: "JX_LOG_FORMAT"
              value: "json"
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: LOGRUS_SERVICE
              value: "lighthouse"
            - name: LOGRUS_SERVICE_VERSION
              value: "1.5.16"
            - name: LOGRUS_STACK_SKIP
              value: ""
            - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
              value: "tekton-bot"
            - name: DEFAULT_PIPELINE_RUN_TIMEOUT
              value: "2h0m0s"
            - name: FILE_BROWSER
              value: "git"
            - name: JX_DEFAULT_IMAGE
              value: "ghcr.io/jenkins-x/builder-maven:2.1.149-768"
            - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
              value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
            - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
              value: "8c0d2af5ca57a30591f66cc7fbac3646384ff07b"
          envFrom:
            - secretRef:
                name: jx-boot-job-env-vars
                optional: true
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
